In [4]:
import numpy as np

np.__version__

'1.24.4'

In [6]:
numere = [1,2,3,4,5]
print(numere, type(numere))

[1, 2, 3, 4, 5] <class 'list'>


In [8]:
arr=np.array([1,2,3,4,5])
arr, type(arr)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

In [9]:
t=[1,2,3,4,5]
arr=np.array(t)
arr, type(arr)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

In [10]:
t=range(3,8)
arr=np.array(t)
arr, type(arr)

(array([3, 4, 5, 6, 7]), numpy.ndarray)

In [12]:
colectie = ["iarna","vara","toamna"]
arr=np.array(colectie)
print("arr=",arr)
print("typearr=",type(arr))
print("dtype=",arr.dtype)

arr= ['iarna' 'vara' 'toamna']
typearr= <class 'numpy.ndarray'>
dtype= <U6


In [14]:
r=range(3,8)
arr=np.array(r)
arr,type(arr),arr.dtype

(array([3, 4, 5, 6, 7]), numpy.ndarray, dtype('int32'))

In [16]:
arr=np.array([20,30,40])
arr, arr.dtype


(array([20, 30, 40]), dtype('int32'))

In [17]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(3,8)

array([3, 4, 5, 6, 7])

In [21]:
np.arange(5,11,2)

array([5, 7, 9])

In [23]:
arr = np.arange(5,11,2)
print(arr)
print("maxx",arr.max())
print("min",arr.min())
print("len=",arr.size)

[5 7 9]
maxx 9
min 5
len= 3


In [24]:
arr = np.arange(5,11,2)
print(arr)
print("maxx",max(arr))
print("min",min(arr))
print("len=",len(arr))

[5 7 9]
maxx 9
min 5
len= 3


In [25]:
arr=np.arange(5,11,2)
print("argmax",arr.argmax())
print("argmin",arr.argmin())

argmax 2
argmin 0


In [26]:
arr=np.arange(10,100,5)
arr[:5]

array([10, 15, 20, 25, 30])

In [27]:
arr=np.arange(10,100,5)
arr+arr

array([ 20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130, 140,
       150, 160, 170, 180, 190])

In [34]:
arr=np.arange(1,10)
arr+arr
arr=arr/2

In [35]:
arr=np.arange(1,10)
arr>2

array([False, False,  True,  True,  True,  True,  True,  True,  True])

In [36]:
arr=np.arange(1,10)
list(filter(lambda x: x>2, arr))

[3, 4, 5, 6, 7, 8, 9]

In [38]:
arr=np.arange(1,10)
arr[arr>2]

array([3, 4, 5, 6, 7, 8, 9])

In [43]:
arr=np.arange(1,10)
arr[arr%3!=0]

array([1, 2, 4, 5, 7, 8])

In [44]:
arr=np.arange(1,10)
arr[(arr%3!=0)&(arr>5)]

array([7, 8])

In [49]:
arr=np.arange(1,10)

nedivizibile_cu_3 = arr %3!=0
mai_mari_ca_5 = arr>5
arr[nedivizibile_cu_3 | mai_mari_ca_5]


array([1, 2, 4, 5, 6, 7, 8, 9])