In [5]:
import numpy as np
# %%
# ######## Exercitiul ################
# Creați un vector cu 10 elemente întregi, toate fiind egale cu 0.

vect=np.zeros(10)
print(vect)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
######### Exercitiul ################
# Creați un vector cu 10 elemente întregi, toate fiind egale cu 1.

vect1=np.ones(10)
print(vect1)



[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [16]:
######### Exercitiul ################
# Creați un vector cu elemente întregi de la 0 la 9.


vect2=np.arange(1,11) - 1
print(vect2 )

[0 1 2 3 4 5 6 7 8 9]


In [15]:
######### Exercitiul ################
# Creați un vector cu elemente întregi de la 10 la 29.

vect3=np.arange(10,30) 
print(vect3 )


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [29]:
######### Exercitiul ################
# Creați un vector cu elemente întregi de la 0 la 9 în ordine inversă.

vect4=np.arange(1,11) - 1
vect4=np.sort(vect4)[::-1]
print(vect4 )



[9 8 7 6 5 4 3 2 1 0]


In [43]:
######### Exercitiul ################
# Creați un vector cu 10 elemente aleatoare între 0 și 1.

vect_random = np.random.rand(10)
print(vect_random)


[0.0611086  0.4127406  0.77471919 0.014449   0.29217505 0.41243
 0.3073014  0.85369381 0.50690209 0.78243724]


In [36]:
######### Exercitiul ################
# Creați o matrice 3x3 cu elemente întregi aleatoare între 0 și 9.

vect4=np.arange(1,10)
print(vect4)
matrice=vect4.reshape(3,3)
print(matrice)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
######### Exercitiul ################
# Creați o matrice identitate 5x5.
matrice2=np.identity(5)
print(matrice2)




[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [41]:
######### Exercitiul ################
# Adunați două matrici de dimensiuni egale (de exemplu, 3x3).

import numpy as np

# Creează două matrici 3x3 cu elemente aleatoare
matrix1 = np.random.rand(3, 3)
matrix2 = np.random.rand(3, 3)

# Adună cele două matrici
matrix_sum = np.add(matrix1, matrix2)

print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\nMatrix Sum:")
print(matrix_sum)


Matrix 1:
[[0.73006551 0.38304076 0.35489533]
 [0.40948494 0.75041337 0.2553623 ]
 [0.57136206 0.61667694 0.65812797]]

Matrix 2:
[[0.9490837  0.26467137 0.64842302]
 [0.22125772 0.25341371 0.06072113]
 [0.35857341 0.5142618  0.79017077]]

Matrix Sum:
[[1.67914921 0.64771213 1.00331835]
 [0.63074265 1.00382708 0.31608343]
 [0.92993546 1.13093874 1.44829874]]


In [42]:
######### Exercitiul ################
# Înmulțiți două matrici de dimensiuni corespunzătoare (de  exemplu, 2x3 și 3x2).

# Creează două matrici 3x3 cu elemente aleatoare
matrix1 = np.random.rand(3, 3)
matrix2 = np.random.rand(3, 3)

# Inmultirea cele două matrici
matrix_sum = np.multiply(matrix1, matrix2)

print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\nMatrix Sum:")
print(matrix_sum)


Matrix 1:
[[0.90065019 0.85016523 0.8710925 ]
 [0.30070219 0.74318983 0.69726232]
 [0.03863581 0.65416829 0.59695276]]

Matrix 2:
[[0.43562669 0.49604792 0.55910598]
 [0.47479081 0.98415946 0.11853977]
 [0.874782   0.97200936 0.72188193]]

Matrix Sum:
[[0.39234726 0.4217227  0.48703303]
 [0.14277064 0.7314173  0.08265331]
 [0.03379791 0.6358577  0.43092941]]


In [45]:
######### Exercitiul ################
# Transpuneți o matrice (de exemplu, 3x4).
matrix1 = np.random.rand(3, 4)
matrix2=matrix1.transpose()


print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)

Matrix 1:
[[0.56522442 0.07160351 0.53569582 0.28619333]
 [0.98976794 0.87876096 0.01378996 0.24984468]
 [0.96172371 0.59869923 0.26768011 0.8991428 ]]

Matrix 2:
[[0.56522442 0.98976794 0.96172371]
 [0.07160351 0.87876096 0.59869923]
 [0.53569582 0.01378996 0.26768011]
 [0.28619333 0.24984468 0.8991428 ]]


In [61]:
######### Exercitiul ################
# Găsiți valoarea maximă dintr-un vector.

arr=np.random.randint(0,10,(1,5))
print(arr)
print(arr, arr.max())

[[1 4 1 5 7]]
[[1 4 1 5 7]] 7


In [64]:
######### Exercitiul ################
# Găsiți indicele valorii maxime dintr-un vector.

arr=np.random.randint(0,10,(1,5))
print(arr)
print(arr, arr.argmax())

[[6 6 4 1 0]]
[[6 6 4 1 0]] 0


In [65]:
######### Exercitiul ################


3


AttributeError: 'int' object has no attribute 'max'

In [ ]:
# Găsiți media aritmetică a valorilor dintr-o matrice.

arr=np.random.randint(0,5)
print(arr)
print(arr, arr.max())

# %%